### ISSUE TITLE
Doesn't put image in dist folder

### ISSUE THREAD

**Issue by edualb** [Kocal/vue-web-extension#563]
**Describe the bug**
When you build your application, the images don't go to dist folder.

**To Reproduce**
1. put a `logo.png` image inside of popup folder
2. alter `App.vue` : 
```
<template>
  <div class="container">
    <p>Hello, World!</p>
    <img src="logo.png">
  </div>
</template>
```
3. run `$ npm run watch:dev` or `$ npm run-script-build`
4. check dist folder without logo.png

**Expected behavior**
creating a logo.png inside of dist folder.

**Desktop (please complete the following information):**
- [vue-web-extension](https://github.com/Kocal/vue-web-extension) version: v1.12.0
 - OS: Linux Ubuntu 18.04
 - Node.js version: v12.16.1

**Comment by ltotsas** [comment]
I also experience this problem. And its unclear how to use images from inside Vue. The webpack creates an output folder 'ímages' but still the image is not loaded from Vue.

**Comment by edualb** [comment]
Hey guys, I found a solution but I forgot to share it here. Sorry.

What we need to do is change the `webpack.config.js` file, I do not know if is the correct way, but I added this line:

```js
   // ...
   new CopyPlugin([
      { from: 'icons', to: 'icons', ignore: ['icon.xcf'] },

      // added  { from: 'popup/images', to: 'popup/images'}
      { from: 'popup/images', to: 'popup/images'},

      { from: 'popup/popup.html', to: 'popup/popup.html', transform: transformHtml },
      { from: 'options/options.html', to: 'options/options.html', transform: transformHtml },
      // ...
```

And I create an image folder inside of the popup folder. Finally, I put my images inside of this folder.

If you want to use your images, just put it in your template `.vue` file:

```html
<img src="images/logo.jpg" width="90" height="125">
```

To test, just run:

```shell
$ npm run build
```
Or if you want to watch your extension app:

```shell
$ npm run watch 
```

**Comment by MihaiVoinea** [comment]
I had a similar problem with fonts.

The way I fixed it was to change `emitFile` for `file-loader` to true:
```js
      {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        loader: "file-loader",
        options: {
          name: "[name].[ext]",
          outputPath: "/fonts/",
          emitFile: true // changed this from false
        }
      }
```

Maybe a similar fix for images will do the trick for you.

**Comment by edualb** [comment]
We need to open a PR to fix it. Unfortunately, I am not having time to do it, when I will have time, I open a PR if it has not solved yet.

If anyone wants to solve it, the solution is here :)

**Comment by Kocal** [comment]
Fixed by #571
